name: Get random password and its hash
author: meysam@licenseware.io
description: Generate random password hash up to 92 character length
branding:
  icon: "credit-card"
  color: "red"
inputs:
  length:
    required: false
    default: 16
  password:
    required: false
    description: will provide a default string if nothing is provided
outputs:
  password:
    description: the actual password, in case you didn't provide the input
  password-hash:
    description: the password hash

runs:
  using: "docker"
  image: "Dockerfile"
  args:
    - --length=${{ inputs.length }}
    - --password=${{ inputs.password }}
